pipeline {
    agent any

    environment {
        TERRAFORM_DIR = 'terraform'
        AWS_ACCESS_KEY_ID = lucky-credentials('aws-access-key-id') 
        AWS_SECRET_ACCESS_KEY = lucky-credentials('aws-secret-access-key') 
        AWS_DEFAULT_REGION = 'us-west-2
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Lucky-Hero-Vired-Projects/Project-1.git', branch: 'main'
            }
        }

        stage('Initialize Terraform') {
            steps {
                dir("${TERRAFORM_DIR}") {
                    sh '''
                        terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("${TERRAFORM_DIR}") {
                    sh '''
                        terraform plan -out=tfplan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("${TERRAFORM_DIR}") {
                    sh '''
                        terraform apply -auto-approve tfplan
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure setup completed successfully.'
        }
        failure {
            echo 'Infrastructure setup failed. Please check logs.'
        }
    }
}
