name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: "Choose Terraform action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TERRAFORM_DIR: terraform
      AWS_DEFAULT_REGION: us-west-2

    steps:
      # Checkout the code repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform
      - name: Initialize Terraform
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      # Plan or destroy based on input
      - name: Execute Terraform Action
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          if [ "${{ github.event.inputs.ACTION }}" == "apply" ]; then
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          elif [ "${{ github.event.inputs.ACTION }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid ACTION input: ${{ github.event.inputs.ACTION }}"
            exit 1
          fi

      # Post success message
      - name: Success Message
        if: success()
        run: echo "Terraform action ${{ github.event.inputs.ACTION }} completed successfully."

      # Post failure message
      - name: Failure Message
        if: failure()
        run: echo "Terraform action ${{ github.event.inputs.ACTION }} failed. Please check logs."
